import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy - Vidality Trading Platform',
  description: 'Privacy Policy for Vidality trading platform. Learn how we collect, use, and protect your personal information.',
}

export default function PrivacyPage() {
  const effectiveDate = "August 31, 2025";

  return (
    <main className="min-h-screen bg-gray-50 text-gray-900 px-6 py-12">
      <div className="max-w-4xl mx-auto bg-white shadow rounded-2xl p-8 md:p-12">
        <header>
          <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
          <p className="text-sm text-gray-600 mb-6">Effective date: {effectiveDate}</p>
        </header>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">1. Introduction</h2>
          <p>
            VIDALITY PTY LTD operates the Vidality trading platform (the "Service"). This Privacy Policy explains what
            personal data we collect, how we use and share it, your rights, and
            the measures we take to protect your information. This Policy
            applies to all users worldwide.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">2. Data Controller</h2>
          <p>
            Data Controller: VIDALITY PTY LTD (ACN 685 187 679) — Registered Office:
            2605, 1 Geoffrey Bolton Avenue, Perth, WA 6000, Australia. For
            privacy inquiries contact: <a href="mailto:amar@vidality.com">amar@vidality.com</a>
            {" "}or{" "}
            <a href="mailto:contact.support.vidality@gmail.com">contact.support.vidality@gmail.com</a>.
          </p>
          </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">3. What we collect</h2>
          <p>We collect the following categories of information:</p>
          <ul className="list-disc pl-6">
            <li><strong>Account & contact data:</strong> name (if provided), email address, profile preferences.</li>
            <li><strong>Authentication data:</strong> hashed passwords, multi-factor authentication metadata.</li>
            <li><strong>Usage & telemetry:</strong> logs, device and browser information, IP address, session times, feature usage.</li>
            <li><strong>Market & simulation data:</strong> paper trading inputs, simulated positions, strategy configurations (these are user-supplied or generated by the Service).</li>
            <li><strong>Support & communications:</strong> support requests, chat logs with our bot (may be stored for quality and compliance).</li>
              </ul>
          <p className="text-sm text-gray-600 mt-2">
            We do not require payment details for paper trading. If/when payment features are enabled, payment processing will be handled by third-party payment processors described in Section 7.
          </p>
          </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">4. How we use data</h2>
          <p>We process personal data for these primary purposes:</p>
          <ul className="list-disc pl-6">
            <li>To provide, operate, and improve the Service (authentication, account management, feature operation).</li>
            <li>To run paper trading simulations, analytics and AI models that generate insights and strategy evaluations.</li>
            <li>To send administrative communications, updates, security alerts, and product announcements.</li>
            <li>To detect, prevent, and respond to fraud, abuse, and security incidents.</li>
            <li>To comply with legal obligations and handle lawful requests (court orders, regulatory requests).</li>
              </ul>
          <p className="text-sm text-gray-600 mt-2">
            Where required by law or contract, we will identify the legal basis for processing (e.g., consent, contract performance, legitimate interests, or legal compliance).
          </p>
          </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">5. AI, model training & automated processing</h2>
          <p>
            Our Service includes AI-powered features and bots that analyze user-supplied data and public market data to produce insights, signals, and simulated strategy outputs. Outputs are generated by automated processing and are used to provide and improve the Service.
          </p>
          <p>
            <strong>Important:</strong> AI outputs and simulated results are for educational and research purposes only and are not financial, legal, or tax advice. We may use anonymized or aggregated interaction data to improve models and system performance; when we use personal data for model training we will disclose this usage and where necessary obtain your consent.
          </p>
          </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">6. Cookies & tracking</h2>
          <p>
            We use cookies, local storage, and similar technologies to operate the Service, remember preferences, enable sign-in, and measure performance. You may control cookie preferences via your browser or our cookie controls where provided.
          </p>
          </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">7. Third parties & data sharing</h2>
          <p>
            We share data with trusted third parties only as necessary to provide the Service. Typical categories include:
          </p>
          <ul className="list-disc pl-6">
            <li>Market data providers and financial data APIs (to power simulated quotes and historical data).</li>
            <li>Analytics and monitoring services (to measure and improve platform performance).</li>
            <li>Payment processors (if/when payments are enabled).</li>
            <li>Cloud infrastructure and database providers.</li>
            <li>Legal, tax or regulatory advisors, when required to comply with law.</li>
              </ul>
          <p className="text-sm text-gray-600 mt-2">
            We enter contracts with third parties to require appropriate data protection controls (data processing agreements) and limit secondary use. We do not sell personal data.
          </p>
          </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">8. International transfers</h2>
          <p>
            VIDALITY PTY LTD operates globally and may transfer or store personal data internationally (including to Australia and other jurisdictions). Where required by law, we implement safeguards (e.g., standard contractual clauses, contractual protections) to protect international transfers.
          </p>
          </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">9. Data retention</h2>
          <p>
            We retain personal data only for as long as necessary to provide the Service, meet legal obligations, resolve disputes, enforce agreements, and for legitimate business purposes such as analytics and improving models. Retention periods vary by data type; account data is retained until account deletion plus a reasonable period for backups and compliance.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">10. Security</h2>
          <p>
            We apply industry-standard administrative, technical, and physical safeguards to protect personal data (encryption in transit, access controls, secure cloud infrastructure, regular audits). However, no system is completely secure; we cannot guarantee absolute security.
          </p>
          </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">11. Data subject rights</h2>
          <p>
            Depending on your jurisdiction, you may have rights including:
          </p>
          <ul className="list-disc pl-6">
            <li>Access to personal data we hold about you;</li>
            <li>Request correction or deletion of inaccurate or unnecessary data;</li>
            <li>Object to or restrict certain processing (including profiling);</li>
            <li>Request portability of your personal data in a structured format;</li>
            <li>Where applicable, withdraw consent to processing for specific purposes;</li>
            <li>Exercise opt-out rights under applicable laws (for example, California residents may have specific rights under CCPA/CPRA).</li>
          </ul>
          <p className="text-sm text-gray-600 mt-2">
            To exercise rights, contact us (see Section 15). We will verify identity before fulfilling requests and respond within applicable legal timeframes.
          </p>
          </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">12. Data breaches</h2>
          <p>
            We maintain incident response and breach notification procedures. If a data breach is likely to result in a risk to individuals' rights and freedoms, we will notify affected individuals and relevant supervisory authorities in accordance with applicable law.
          </p>
          </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">13. Children's data</h2>
          <p>
            The Service is not directed to children under 16. We do not knowingly collect personal data from children under applicable age thresholds. If we become aware we have collected such data, we will take steps to delete it.
          </p>
          </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">14. Changes to this Policy</h2>
          <p>
            We may modify this Privacy Policy. Material changes will be published with a revised effective date and, where required, notified to users.
          </p>
          </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">15. Contact</h2>
          <p>
            For privacy questions, data requests, or complaints contact:
          </p>
          <ul className="list-disc pl-6">
            <li>Email: <a href="mailto:amar@vidality.com">amar@vidality.com</a></li>
            <li>Support: <a href="mailto:contact.support.vidality@gmail.com">contact.support.vidality@gmail.com</a></li>
            <li>Registered Office: 2605, 1 Geoffrey Bolton Avenue, Perth, WA 6000, Australia</li>
          </ul>
          </section>

        <footer className="text-sm text-gray-500 mt-6">
          © 2025 VIDALITY PTY LTD. All rights reserved.
        </footer>
        </div>
    </main>
  );
}
